# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c93d251d66ca8c9142bc9d66b4f4024e5a1db7a23e2094002b1ce935e0616f97702939140238602395cbc271e46885d2904d39057467bc87e8ae9755a3a442d1

test:
  secret_key_base: b506f73f64965c8bbdf11381b80089392b147445d2c317688c7a0dff42b07c31807639a3c8e3cea29aa13a421f57aebbfa71d7e1d4211e1a2740311933b7c23d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
